### ISSUE TITLE
Transparent Proxy REDIRECT mode not working correctly for IPv6

### ISSUE THREAD

**Issue by ninjken** [go-gost/x#38]
Server B needs to access redis(port 6379) and other services on Server A

Server A configuration
IPv6 _fd12:3456:789a:1::1_
gost.yml
```yml
services:
  - name: tsin_tunnel
    addr: "[fd12:3456:789a:1::1]:10001"
    listener:
      type: tcp
    handler:
      type: socks5
```
Server B configuration
IPv6 _fd12:3456:789a:2::ebb_
gost.yml
```yml
services:
  - name: tsin_tunnel
    addr: "[fd12:3456:789a:2::ebb]:10001"
    handler:
      type: red
      chain: chain-0
    listener:
      type: red

chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: "[fd12:3456:789a:1::1]:10001"
            connector:
              type: socks5
            dialer:
              type: tcp
```

`iptables` command run on Server B, in order to redirect traffic
```bash
ip6tables -t nat -A OUTPUT -p tcp --match multiport --dports 6379 -j DNAT --to-destination [fd12:3456:789a:2::ebb]:10001
```

After gost is started on both Server A and B, I tried to connect to Server A's redis from Server B
> tsuser@tsin:~$ redis-cli -h fd12:3456:789a:1::1
> [fd12:3456:789a:1::1]:6379> keys *
> Error: Connection reset by peer

and gost on Server A logs
> {"duration":6147707,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"[fd12:3456:789a:1::1]:10001","msg":"[fd12:3456:789a:2::ebb]:23368 >< [fd12:3456:789a:1::1]:10001","remote":"[fd12:3456:789a:2::ebb]:23368","service":"tsin_tunnel","time":"2024-12-11T16:36:28.978+08:00"}
{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"dial tcp [fd12:3456:789a:1::1]:60184: connect: connection refused","service":"tsin_tunnel","time":"2024-12-11T16:36:28.978+08:00"}

gost service on Server A is trying to connect to port 60184 instead of 6379, and I noticed that in hex format
6379 is 0x18eb
60184 is 0xeb18
so I believe the port is somehow wrong in endianness
