### ISSUE TITLE
SIGSEGV when no dialer specified

### ISSUE THREAD

**Issue by vanym** [go-gost/x#4]
App crashes when connector specified and dialer not specified

```
$ ./gost-linux-amd64-3.0.0-rc.0 -C configv3nodialer.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc32db]

goroutine 1 [running]:
github.com/go-gost/x/config/parsing.ParseHop(0xc00053ea20)
        /home/gerry/code/go-gost/x/config/parsing/chain.go:89 +0x3db
github.com/go-gost/x/config/parsing.ParseChain(0xc000635a10)
        /home/gerry/code/go-gost/x/config/parsing/chain.go:46 +0x2a5
main.buildService(0xc000570420)
        /home/gerry/code/go-gost/gost/cmd/gost/config.go:109 +0xd6d
main.main()
        /home/gerry/code/go-gost/gost/cmd/gost/main.go:143 +0x7eb
```

##### To Reproduce
`configv3nodialer.yaml`
```
services:
- name: socks-0
  addr: ":1080"
  handler:
    type: socks5
    chain: chain-0
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 127.0.0.1:9050
      connector:
        type: socks5
#      dialer:
#        type: tcp
```
Run
`./gost-linux-amd64-3.0.0-rc.0 -C configv3nodialer.yaml`

##### Expected behavior
Do not crash in this case. I guess app should just use tcp dialer as default
