### ISSUE TITLE
Socks5 client provides userpass auth method even when no auth configured

### ISSUE THREAD

**Issue by vanym** [go-gost/x#6]
Socks5 connector always provides userpass auth method
This is not expected behavior and cause problems with some socks5 servers
[Dante socks5 server](https://github.com/wernight/docker-dante) select userpass over no auth and gost provide empty userpass

##### To Reproduce
Run dante server in docker
`docker run -d -p 127.0.0.1:1080:1080 wernight/dante`
Configure gost
`configv3dante.yaml`
```
services:
- name: socks-0
  addr: ":1082"
  handler:
    type: socks5
    chain: chain-0
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 127.0.0.1:1080
      connector:
        type: socks5
      dialer:
        type: tcp
```
Run gost
`./gost-linux-amd64-3.0.0-rc.0 -C configv3dante.yaml`
Try request to dante directly
`curl --socks5-hostname "127.0.0.1:1080" -v "https://ifconfig.me"`
Try request to gost
`curl --socks5-hostname "127.0.0.1:1082" -v "https://ifconfig.me"`
You will see `auth failure` in gost output

You can use wireshark to see problem in authentication detailly

##### Expected behavior
Do not add userpass client auth method if auth not configured
